# Generated by Django 6.0.1 on 2026-01-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbeitszeit', '0003_alter_arbeitszeitvereinbarung_antragsart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schichttyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('kuerzel', models.CharField(max_length=5, unique=True, verbose_name='Kürzel')),
                ('start_zeit', models.TimeField(verbose_name='Start-Zeit')),
                ('ende_zeit', models.TimeField(verbose_name='Ende-Zeit')),
                ('farbe', models.CharField(choices=[('#4CAF50', 'Grün'), ('#2196F3', 'Blau'), ('#FF9800', 'Orange'), ('#9C27B0', 'Lila'), ('#F44336', 'Rot'), ('#607D8B', 'Grau')], default='#4CAF50', max_length=7, verbose_name='Farbe')),
                ('pausenzeit_minuten', models.IntegerField(default=30, verbose_name='Pausenzeit (Minuten)')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schichttyp',
                'verbose_name_plural': 'Schichttypen',
                'ordering': ['start_zeit'],
            },
        ),
        migrations.CreateModel(
            name='Schichtplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_datum', models.DateField(verbose_name='Start-Datum')),
                ('ende_datum', models.DateField(verbose_name='Ende-Datum')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('veroeffentlicht', 'Veröffentlicht'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('bemerkungen', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_schichtplaene', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Schichtplan',
                'verbose_name_plural': 'Schichtpläne',
                'ordering': ['-start_datum'],
            },
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('abweichende_start_zeit', models.TimeField(blank=True, null=True, verbose_name='Abweichende Start-Zeit')),
                ('abweichende_ende_zeit', models.TimeField(blank=True, null=True, verbose_name='Abweichende Ende-Zeit')),
                ('bemerkungen', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='arbeitszeit.mitarbeiter', verbose_name='Mitarbeiter')),
                ('schichtplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='schichtplan.schichtplan', verbose_name='Schichtplan')),
                ('schichttyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schichtplan.schichttyp', verbose_name='Schichttyp')),
            ],
            options={
                'verbose_name': 'Schicht',
                'verbose_name_plural': 'Schichten',
                'ordering': ['datum', 'schichttyp__start_zeit'],
                'unique_together': {('schichtplan', 'mitarbeiter', 'datum', 'schichttyp')},
            },
        ),
        migrations.CreateModel(
            name='Schichttausch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('genehmigt', 'Genehmigt (Planer)'), ('abgebrochen', 'Abgebrochen')], default='offen', max_length=20, verbose_name='Status')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bearbeitet_am', models.DateTimeField(auto_now=True)),
                ('angeboten_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebotene_tausche', to='arbeitszeit.mitarbeiter', verbose_name='Angeboten von')),
                ('gewuenschter_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gewuenschte_tausche', to='arbeitszeit.mitarbeiter', verbose_name='Gewünschter Tauschpartner')),
                ('urspruengliche_schicht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tausch_angebote', to='schichtplan.schicht', verbose_name='Ursprüngliche Schicht')),
            ],
            options={
                'verbose_name': 'Schichttausch',
                'verbose_name_plural': 'Schichttausche',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Schichtwunsch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('nicht_verfuegbar', models.BooleanField(default=False, help_text='z.B. Urlaub, Krankheit, privater Termin', verbose_name='Nicht verfügbar')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bevorzugte_schichttypen', models.ManyToManyField(blank=True, to='schichtplan.schichttyp', verbose_name='Bevorzugte Schichttypen')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichtwuensche', to='arbeitszeit.mitarbeiter', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Schichtwunsch',
                'verbose_name_plural': 'Schichtwünsche',
                'ordering': ['datum'],
                'unique_together': {('mitarbeiter', 'datum')},
            },
        ),
    ]
