# Generated by Django 6.0.1 on 2026-01-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0004_mitarbeiter_arbeitszeit_typ_and_more'),
        ('schichtplan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schichtwunsch',
            options={'ordering': ['datum', 'mitarbeiter'], 'verbose_name': 'Schichtwunsch', 'verbose_name_plural': 'Schichtwünsche'},
        ),
        migrations.RemoveField(
            model_name='schicht',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schicht',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schichttyp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schichttyp',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schichtwunsch',
            name='bemerkung',
        ),
        migrations.RemoveField(
            model_name='schichtwunsch',
            name='bevorzugte_schichttypen',
        ),
        migrations.RemoveField(
            model_name='schichtwunsch',
            name='nicht_verfuegbar',
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='begruendung',
            field=models.TextField(blank=True, help_text='Optional: Grund für Wunsch'),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='benoetigt_genehmigung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='genehmigt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='genehmigt_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='genehmigt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genehmigte_wuensche', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='wunsch',
            field=models.CharField(choices=[('urlaub', '1 - Urlaub'), ('kein_tag_aber_nacht', '2 - Kein Tag, aber Nacht möglich'), ('keine_nacht_aber_tag', '3 - Keine Nacht, aber Tag möglich'), ('tag_bevorzugt', '4 - Tag bevorzugt'), ('nacht_bevorzugt', '5 - Nacht bevorzugt'), ('gar_nichts', '6 - Gar nichts möglich'), ('zusatzarbeit', '7 - Zusatzarbeit')], default='tag_bevorzugt', help_text='Wunsch-Kategorie (1-7)', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schicht',
            name='abweichende_ende_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='abweichende_start_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='bemerkungen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='arbeitszeit.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='schichtplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='schichtplan.schichtplan'),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='schichttyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schichtplan.schichttyp'),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='aktualisiert_am',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='bemerkungen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='ende_datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='erstellt_von',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='start_datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('veroeffentlicht', 'Veröffentlicht'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20),
        ),
        migrations.AlterField(
            model_name='schichttausch',
            name='angeboten_von',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebotene_tausche', to='arbeitszeit.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='schichttausch',
            name='gewuenschter_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erhaltene_tausch_anfragen', to='arbeitszeit.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='schichttausch',
            name='nachricht',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schichttausch',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('genehmigt', 'Genehmigt'), ('abgebrochen', 'Abgebrochen')], default='offen', max_length=20),
        ),
        migrations.AlterField(
            model_name='schichttausch',
            name='urspruengliche_schicht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tausch_anfragen', to='schichtplan.schicht'),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='ende_zeit',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='farbe',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='kuerzel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='pausenzeit_minuten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schichttyp',
            name='start_zeit',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichtwuensche', to='arbeitszeit.mitarbeiter'),
        ),
        migrations.CreateModel(
            name='SchichtwunschPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Wünsche für März 2026'", max_length=100)),
                ('fuer_monat', models.DateField(help_text='Für welchen Monat sind die Wünsche (z.B. 2026-03-01)')),
                ('eingabe_start', models.DateTimeField(help_text='Ab wann können Wünsche eingegeben werden')),
                ('eingabe_ende', models.DateTimeField(help_text='Bis wann können Wünsche eingegeben werden')),
                ('status', models.CharField(choices=[('vorbereitung', 'In Vorbereitung'), ('offen', 'Offen - Wünsche können eingereicht werden'), ('geschlossen', 'Geschlossen - Wird geplant'), ('genehmigung', 'Wünsche werden genehmigt'), ('planung', 'Plan wird generiert'), ('veroeffentlicht', 'Plan ist veröffentlicht')], default='vorbereitung', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erstellte_wunschperioden', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schichtwunsch-Periode',
                'verbose_name_plural': 'Schichtwunsch-Perioden',
                'ordering': ['-fuer_monat'],
            },
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='periode',
            field=models.ForeignKey(blank=True, help_text='Zu welcher Wunschperiode gehört dieser Wunsch', null=True, on_delete=django.db.models.deletion.CASCADE, to='schichtplan.schichtwunschperiode'),
        ),
    ]
