# Generated by Django 6.0.1 on 2026-02-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0010_monatlichearbeitszeitsoll'),
        ('schichtplan', '0004_delete_mitarbeiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schichttausch',
            name='bearbeitet_am',
        ),
        migrations.RemoveField(
            model_name='schichtwunsch',
            name='aktualisiert_am',
        ),
        migrations.AddField(
            model_name='schichtplan',
            name='wunschperiode',
            field=models.ForeignKey(blank=True, help_text='Wähle die Wunschperiode aus, die als Basis für diesen Plan dient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schichtplaene', to='schichtplan.schichtwunschperiode'),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='begruendung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schichtplan.schichtwunschperiode'),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='wunsch',
            field=models.CharField(choices=[('urlaub', '1 - Urlaub'), ('kein_tag_aber_nacht', '2 - Kein Tag, aber Nacht möglich'), ('keine_nacht_aber_tag', '3 - Keine Nacht, aber Tag möglich'), ('tag_bevorzugt', '4 - Tag bevorzugt'), ('nacht_bevorzugt', '5 - Nacht bevorzugt'), ('gar_nichts', '6 - Gar nichts möglich'), ('zusatzarbeit', '7 - Zusatzarbeit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schichtwunschperiode',
            name='eingabe_ende',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schichtwunschperiode',
            name='eingabe_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schichtwunschperiode',
            name='fuer_monat',
            field=models.DateField(help_text='z.B. 2026-03-01'),
        ),
        migrations.AlterField(
            model_name='schichtwunschperiode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='schicht',
            unique_together={('schichtplan', 'mitarbeiter', 'datum')},
        ),
    ]
