# Generated by Django 6.0.1 on 2026-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0010_monatlichearbeitszeitsoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='erlaubte_wochentage',
            field=models.JSONField(blank=True, help_text='Nur bestimmte Tage: [0]=Mo, [1]=Di, [2]=Mi, [3]=Do, [4]=Fr, [5]=Sa, [6]=So. Leer = alle Tage erlaubt.', null=True, verbose_name='Erlaubte Arbeitstage'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='keine_zusatzdienste',
            field=models.BooleanField(default=False, help_text='Wenn aktiv: MA wird NICHT in Zusatzdienste eingeteilt', verbose_name='Keine Zusatzdienste'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='kann_nachtschicht',
            field=models.BooleanField(default=True, verbose_name='Kann Nachtschichten arbeiten'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='kann_tagschicht',
            field=models.BooleanField(default=True, verbose_name='Kann Tagschichten arbeiten'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='max_wochenenden_pro_monat',
            field=models.IntegerField(default=4, help_text='0 = keine Wochenenden, 4 = alle möglich', verbose_name='Max. Wochenenden pro Monat'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='nachtschicht_nur_wochenende',
            field=models.BooleanField(default=False, help_text='Wenn aktiv: Nachtschichten nur Freitag, Samstag, Sonntag', verbose_name='Nachtschicht nur Fr/Sa/So'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='verfuegbarkeit',
            field=models.CharField(blank=True, choices=[('voll', 'Vollzeit - alle Schichten'), ('teilzeit', 'Teilzeit - begrenzte Schichten'), ('wochenende_only', 'Nur Wochenende (Fr/Sa/So)'), ('wochentags_only', 'Nur Wochentags (Mo-Do)'), ('dauerkrank', 'Dauerkrank - nicht einplanbar')], default='voll', max_length=20, verbose_name='Verfügbarkeit'),
        ),
    ]
